# Generated by Django 3.0.7 on 2020-06-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacting', '0002_auto_20200618_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
