# Generated by Django 3.0.7 on 2020-06-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacting', '0005_auto_20200618_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
