# Generated by Django 3.0.7 on 2020-06-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacting', '0006_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
