# Generated by Django 3.0.7 on 2020-09-27 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacting', '0009_auto_20200927_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='contacting.Category'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.IntegerField(choices=[(1, 'Mobile'), (2, 'Home'), (3, 'Work')]),
        ),
    ]
